"""Python client for Wity, the typed-decision API."""

from .client import DEFAULT_BASE_URL, DEFAULT_MAX_RETRIES, DEFAULT_TIMEOUT, AsyncWityClient, WityClient
from .errors import (
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    InsufficientBalanceError,
    InternalServerError,
    RateLimitError,
    WityError,
)
from .questions import choice, noul, score
from .types import (
    Answer,
    Choice,
    ChoiceAnswer,
    GenerateResponse,
    Noul,
    NoulAnswer,
    NoulCriteria,
    OtherAnswer,
    Question,
    Reasoning,
    ReasoningInfo,
    Score,
    ScoreAnswer,
    State,
    SystemOneResponse,
    Usage,
)

__version__ = "0.1.0"

__all__ = [
    "DEFAULT_BASE_URL",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_TIMEOUT",
    "APIConnectionError",
    "APIError",
    "APITimeoutError",
    "Answer",
    "AsyncWityClient",
    "AuthenticationError",
    "BadRequestError",
    "Choice",
    "ChoiceAnswer",
    "GenerateResponse",
    "InsufficientBalanceError",
    "InternalServerError",
    "Noul",
    "NoulAnswer",
    "NoulCriteria",
    "OtherAnswer",
    "Question",
    "RateLimitError",
    "Reasoning",
    "ReasoningInfo",
    "Score",
    "ScoreAnswer",
    "State",
    "SystemOneResponse",
    "Usage",
    "WityClient",
    "WityError",
    "choice",
    "noul",
    "score",
]
